### ISSUE TITLE
What should we call this and where should it live?

### ISSUE THREAD

**Issue by jasonrhodes** [node-forward/welcome#2]
We just had a good call to talk about next steps and it seems like we need some individual discussions. First, what should this thing be called and then where should it lived?

Options discussed so far:
- Keep moving with http://knode.io (PRO: it already exists, CON: name is a little kludgy and not necessarily obvious)
- Petition to put stuff on http://nodejs.org (PRO: official, findability, CON: harder to move fast)

Anyone have other ideas?

**Comment by mikeal** [comment]
Alternatively:
- `welcome.nodeschool.io`
- `welcome-to-node.com`

Anything "official" will get stuck in the process Joyent has around the existing website and core, I'd suggest avoiding the official website.

**Comment by mikeal** [comment]
BTW, I should have mentioned, I don't think that where it lives is the most important thing at all. With NodeSchool there were workshoppers and in person stuff happening before the name was even created. Also, if you do end up naming it something unique a good name might come to you based on the content and flow.

**Comment by jasonrhodes** [comment]
@mikeal I think you're right, really -- but we need to pick a place to _start_ at least. Just to get things rolling for where to put some of this content. Doesn't have to be the Final Form Awesome Name at all. :)

**Comment by jasonrhodes** [comment]
Another fast alternative seems like it could be mapping something like [nodeforward.io](https://domai.nr/nodeforward/with/nodeforward.io) to this org and then running /welcome like the NodeSchool chapters run, but I have no idea if the node-forward org is too tied up in other goals for it to be useful in that way?

**Comment by hackygolucky** [comment]
I think I dig welcome-to-node.com or hello-node.com Seems to capture the
intent best.

**Comment by jasonrhodes** [comment]
Both hellonode.io and hellonode.org are available, or I think hello.nodeschool.io or welcome.nodeschool.io would both be fine places to start out, too, especially if we are thinking like @olizilla [mentions here](https://github.com/node-forward/welcome/issues/3#issuecomment-55808850), about making this more obviously integrated with the nodeschool system…

**Comment by zwigby** [comment]
My vote hellonode.io

Charlie

**Comment by hackygolucky** [comment]
howdy all!
@jasonrhodes @olizilla 

Talked to Max Ogden today about nodeschool, and had a conversation about this project working alongside it. The thought was that there's certainly a lot of overlap, but that "what nodeschool is good for right now is: organizing communities (using our chapters approach) and centralizing shared curriculum (workshoppers)...so if it's stuff we can do primarily on github and it would benefit nodeschool chapters then it would make sense."
At the mention of the breakdown of the project, the thought that it would be better suited as a standalone resource that maybe a nodeschool intro to node workshop could be built around.

The idea is to keep nodeschool decentralized and growing by the chapters own energies. Which seems to be counter to what we're looking to do as a central resource. They're happy to let it live as a repo on the nodeschool org if that could benefit us, however.

So I think my opinion stands with @zwigby with hello-node.com or welcome-to-node.com

**Comment by jasonrhodes** [comment]
Sounds fine to me and I'm happy to grab hellonode.io and donate it to the cause. (I'm not a huge fan of dash URLs if we can avoid it and nodeschool among others have already established the .io pattern)

**Comment by hackygolucky** [comment]
Awesome, Jason!

**Comment by olizilla** [comment]
Thinking out loud, I guess I see this group as a task-force rather than a separate initiative. 

The goal is to make sure that there is a coherent story for people getting started with node, both those new to coding and those coming from other languages, and that all the best documentation is well sign posted, accessible, and as much as possible, translated.

Nodeschool's decentralisation is encouraging people all over the world to set up local groups. I'm hoping that those groups bloom into amazing resources for explaining the node concepts to their catchment area using more useful local language & colloquial terminology. If we can make sure that they all have access to mentors and teaching resources, then we can help catalyse that.

I see us as the folks joining the dots between the official node & npm docs, mailing lists, irc, nodeschool and any other initiatives that are helping people level up; Ensuring that the best bits get bubbled up and reused, and encouraging more input from others by liberally spreading the +1 credits.

The more I look into this, the more I see that @hackygolucky  and @jasonrhodes have been pushing [this sort of thing](https://www.npmjs.org/package/welcome-to-node) for ever, so I'm really trying to say _"YAY! Let's do this"_ while also saying, I think we should focus our efforts on improving existing sites (api docs, nodeschool.io) 

...but homepages are fun so I'm all +1 for hellonode.io if just as a billboard for attracting more people to the cause.

**Comment by olizilla** [comment]
In other news, i'm duty bound to warn y'all that it turns out `.io` domains line the pockets of the UK after some dubious land-grabbings. https://gigaom.com/2014/06/30/the-dark-side-of-io-how-the-u-k-is-making-web-domain-profits-from-a-shady-cold-war-land-deal/
...the solution there is probably to lobby the UK government to remunerate the right people rather than avoiding `.io` domains.

**Comment by jasonrhodes** [comment]
If there aren't any objections to .org for now, I'll just get hellonode.org and we'll get started with that. It doesn't matter too much for now, .io is expensive and has some controversy around it, and we aren't sure where this stuff is gonna end up. I'm still intrigued by the nodeschool / hellonode relationship too so I think this is a good plan to get the ball rolling. 

I'll leave this up for a day or two in case anyone has any major objections, then I'm gonna buy the .org domain, close this issue and consider this resolved so we can move onto the actually important stuff! :)

**Comment by hackygolucky** [comment]
Sounds good to me.

**Comment by olizilla** [comment]
:+1:

**Comment by zwigby** [comment]
+1

**Comment by mikeal** [comment]
Related: I started working on a "learning javascript/programming" workshop for NodeSchool https://github.com/mikeal/learnjs

It's about half way done, should be ready for the next NodeSchool Oakland.

**Comment by jasonrhodes** [comment]
Ugh, I dropped the ball on this one. I've got hellonode.org now so I'll probably point this gh-pages stuff that @mikeal did at that domain so we can take a look and start iterating on it. Nothing like something real to motivate people into giving opinions...

I'm also gonna go through all of the comments here again, and the Google Doc @hackygolucky put together from our phone calls, and see what we were talking about as next/first steps.
