### ISSUE TITLE
Mentors program

### ISSUE THREAD

**Issue by mikeal** [node-forward/welcome#6]
I saw that the mentors program came up again during the last meeting.

While I wasn't there I imagine it was similar to what we had discussed at KnodeCamp back in March.

The more I think about this idea the more I love it but also I feel like we're _way_ over-engineering it.

How does this sound as a "Mentors MVP":
- New repo in `node-forward` called `mentors`
- Gitter room for the repo.
- README includes a list of registered mentors.
- README encouraging potential mentors to watch the repo, join the gitter channel, and once they can commit to send a PR to add themselves to the README.
- README encourages people who want mentors to simply log an issue with their experience and interests or to just log on to the gitter channel and do the same.

The goal would be to reduce the process as much as possible so there is as little friction as possible for people signing up on both sides and connecting.

If we start to have problems like "too many mentors/students" we can solve those as they come :)

**Comment by hackygolucky** [comment]
Sounds great. 

A few concerns:
1. facilitators--if we go the aforementioned route, we'll need facilitators for the Gitter room, mentors, and mentees. Who mentors the mentors? :smiley_cat: Who keeps things on track and ensures this stays a welcoming space?
2. People talking about their comfort/experience level publicly(newer programmers, while needing to learn open workflow, don't always feel comfortable doing this--this is a barrier)

Thanks for laying this out, @mikeal and providing insight.

**Comment by rosskukulinski** [comment]
hey @mikeal I completely agree that we were over-engineering.

Some general thoughts:
- I'm concerned this Gitter room _could_ turn into another IRC channel just on another medium.  Just random questions/answers flying back and forth
- One of the things that attracted me to the idea of the mentor program was being paired with a handful of mentees.  I want to form friendships with the people I help because someday they'll know more than I do -- and when that day comes I want to learn from them!
- One of the things we talked about early on was mentoring mentors... helping them to become better teachers as well as ensuring high-standards for the community we're building.  This could be as simple as a Mentor-README.
- It probably wouldn't hurt to have a Mentee-README that explains the goals and expectations.

I guess, I'm sorta thinking that when I list myself as a mentor in the README, I'd like to allocate X slots (3-5?) of mentees that I'm willing to spend an hour or two a week each answering questions, looking at code, talking shop.  As my mentees become self-sufficient, I in turn will encourage them to be mentors, and then I can open up slots for more people.

**Comment by hackygolucky** [comment]
Also, would this be a separate gitter channel? I'll assume that would be
node-forward/mentors too?

**Comment by mikeal** [comment]
> facilitators

Again, I think this is a problem we won't have for a while. The early list of mentors will be the people familiar enough with Node to even see this as a thing. Once we have a bunch of junior mentors we can worry about facilitators.

Also, mentors will step in to facilitate. Like, if someone wants a Browserify mentor I can look through the list of mentors an @ mention all the browserify people.

> People talking about their comfort/experience level publicly

This is a very good point. Once we have this setup let's investigate a good way to either:
- Anonymize new Issue creation.
- Have a private mailing list for just this case.

> Gitter room could turn into another IRC channel just on another medium

We just setup a `help` room for this kind of general Q&A. In the docs we should mention it as a forum for asking questions as opposed to finding mentors.

> mentoring mentors

yes! should probably list as part of "the program" in the README and then, down the line when students are ready to be mentors, we can execute on it.

> form friendships with the people I help

So, the Issue and gitter system is basically just a good way to **pair** up the mentors and mentees. From there it should be a more personal relationship across whatever mediums the mentor/mentee is comfortable with.

> Mentee-README

I think a README / website should speak _first_ to mentees and then, below the fold, to mentors. We should hope to have more mentees than mentors, and mentors need to know the perception of the program from the mentee side in order to get what they are signing up for anyway.

> I'd like to allocate X slots (3-5?) of mentees that I'm willing to spend an hour or two a week each answering questions

Great idea! Perhaps we can use a simple markdown table that can list specialties, number of mentee slots, time avaiable, etc.

> node-forward/mentors channel

Maybe it's better if we call the repo `mentorship` and have a single room for now. In the beginning stages, as we're iterating and figuring out what works, I feel like both sides benefit from seeing as much as possible.

**Comment by RichFromGalvanize** [comment]
Hey guys! Got introduced through @fiveisprime and he is trying to explain how it all works. If I could make a suggestion, I think it would be important to be more specific on what exactly mentors are expected to do, what level of commitment is expected, and who they should "report" to about how to best go about starting. Right now, at least from what I can see, its a very vague thing and I find it hard to determine if I can/want to be part of the program mainly because these questions are still very open.

Then again, I may just be missing where this information is.

**Comment by Fishrock123** [comment]
:+1:

> People talking about their comfort/experience level publicly

Yeah, a private thing would probably be good, but imo we should encourage them as much as possible to go public.

If you have anyone who isn't comfortable with their experience, feel free to also send them to me if you see fit. I'm not exactly the most experienced/educated person, and I still struggle with that fact regarding my value in the industry and sometimes discussions haha. That being said I'd be more than willing to talk with or encourage anyone regarding this.

**Comment by jasonrhodes** [comment]
This conversation is moving along now at https://github.com/node-forward/mentors
